service: sls-elm

provider:
  name: aws
  runtime: nodejs4.3

# The webpack plugin will transpile elm to JavaScript
plugins:
  - serverless-webpack
custom:
  webpack: ./webpack.config.js

functions:
  api:
    handler: api.handler # Refers to function `handler` exported from `api.js`
    events:
      # The following sets up Lambda Proxy Integration
      # Basically, the elm app will do the routing instead of
      # API Gateway
      - http:
          integration: lambda-proxy
          path: /
          method: ANY
      - http:
          integration: lambda-proxy
          path: /{proxy+}
          method: ANY
